/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisningarRouteImport } from './routes/visningar'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as ListorRouteImport } from './routes/listor'
import { Route as KunderRouteImport } from './routes/kunder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjektIndexRouteImport } from './routes/objekt.index'
import { Route as ObjektNyttRouteImport } from './routes/objekt.nytt'
import { Route as ObjektSlugRouteImport } from './routes/objekt.$slug'
import { Route as KunderIdRouteImport } from './routes/kunder.$id'

const VisningarRoute = VisningarRouteImport.update({
  id: '/visningar',
  path: '/visningar',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const ListorRoute = ListorRouteImport.update({
  id: '/listor',
  path: '/listor',
  getParentRoute: () => rootRouteImport,
} as any)
const KunderRoute = KunderRouteImport.update({
  id: '/kunder',
  path: '/kunder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjektIndexRoute = ObjektIndexRouteImport.update({
  id: '/objekt/',
  path: '/objekt/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjektNyttRoute = ObjektNyttRouteImport.update({
  id: '/objekt/nytt',
  path: '/objekt/nytt',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjektSlugRoute = ObjektSlugRouteImport.update({
  id: '/objekt/$slug',
  path: '/objekt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KunderIdRoute = KunderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KunderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kunder': typeof KunderRouteWithChildren
  '/listor': typeof ListorRoute
  '/statistik': typeof StatistikRoute
  '/visningar': typeof VisningarRoute
  '/kunder/$id': typeof KunderIdRoute
  '/objekt/$slug': typeof ObjektSlugRoute
  '/objekt/nytt': typeof ObjektNyttRoute
  '/objekt/': typeof ObjektIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kunder': typeof KunderRouteWithChildren
  '/listor': typeof ListorRoute
  '/statistik': typeof StatistikRoute
  '/visningar': typeof VisningarRoute
  '/kunder/$id': typeof KunderIdRoute
  '/objekt/$slug': typeof ObjektSlugRoute
  '/objekt/nytt': typeof ObjektNyttRoute
  '/objekt': typeof ObjektIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kunder': typeof KunderRouteWithChildren
  '/listor': typeof ListorRoute
  '/statistik': typeof StatistikRoute
  '/visningar': typeof VisningarRoute
  '/kunder/$id': typeof KunderIdRoute
  '/objekt/$slug': typeof ObjektSlugRoute
  '/objekt/nytt': typeof ObjektNyttRoute
  '/objekt/': typeof ObjektIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kunder'
    | '/listor'
    | '/statistik'
    | '/visningar'
    | '/kunder/$id'
    | '/objekt/$slug'
    | '/objekt/nytt'
    | '/objekt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kunder'
    | '/listor'
    | '/statistik'
    | '/visningar'
    | '/kunder/$id'
    | '/objekt/$slug'
    | '/objekt/nytt'
    | '/objekt'
  id:
    | '__root__'
    | '/'
    | '/kunder'
    | '/listor'
    | '/statistik'
    | '/visningar'
    | '/kunder/$id'
    | '/objekt/$slug'
    | '/objekt/nytt'
    | '/objekt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KunderRoute: typeof KunderRouteWithChildren
  ListorRoute: typeof ListorRoute
  StatistikRoute: typeof StatistikRoute
  VisningarRoute: typeof VisningarRoute
  ObjektSlugRoute: typeof ObjektSlugRoute
  ObjektNyttRoute: typeof ObjektNyttRoute
  ObjektIndexRoute: typeof ObjektIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visningar': {
      id: '/visningar'
      path: '/visningar'
      fullPath: '/visningar'
      preLoaderRoute: typeof VisningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listor': {
      id: '/listor'
      path: '/listor'
      fullPath: '/listor'
      preLoaderRoute: typeof ListorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunder': {
      id: '/kunder'
      path: '/kunder'
      fullPath: '/kunder'
      preLoaderRoute: typeof KunderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekt/': {
      id: '/objekt/'
      path: '/objekt'
      fullPath: '/objekt/'
      preLoaderRoute: typeof ObjektIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekt/nytt': {
      id: '/objekt/nytt'
      path: '/objekt/nytt'
      fullPath: '/objekt/nytt'
      preLoaderRoute: typeof ObjektNyttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekt/$slug': {
      id: '/objekt/$slug'
      path: '/objekt/$slug'
      fullPath: '/objekt/$slug'
      preLoaderRoute: typeof ObjektSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunder/$id': {
      id: '/kunder/$id'
      path: '/$id'
      fullPath: '/kunder/$id'
      preLoaderRoute: typeof KunderIdRouteImport
      parentRoute: typeof KunderRoute
    }
  }
}

interface KunderRouteChildren {
  KunderIdRoute: typeof KunderIdRoute
}

const KunderRouteChildren: KunderRouteChildren = {
  KunderIdRoute: KunderIdRoute,
}

const KunderRouteWithChildren =
  KunderRoute._addFileChildren(KunderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KunderRoute: KunderRouteWithChildren,
  ListorRoute: ListorRoute,
  StatistikRoute: StatistikRoute,
  VisningarRoute: VisningarRoute,
  ObjektSlugRoute: ObjektSlugRoute,
  ObjektNyttRoute: ObjektNyttRoute,
  ObjektIndexRoute: ObjektIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
